users:
  - username: admin
    passwordHash: "$2a$10$6fN8DqzlUbQfQ61WQ9r9xus8Ok2acIP4R2f8rQhI4QjCGQ2a5XJ6e"
    role: ADMIN
  - username: user1
    passwordHash: "$2a$10$6fN8DqzlUbQfQ61WQ9r9xus8Ok2acIP4R2f8rQhI4QjCGQ2a5XJ6e"
    role: USER
